
#define UC_LIST(F, S) \
  F(udata_setCommonData) \
  S(u_strToUpper) \
  S(u_strToLower) \
  F(u_strlen) \
  F(u_countChar32) \
  F(u_strHasMoreChar32Than) \
  F(u_strcat) \
  F(u_strncat) \
  F(u_strstr) \
  S(u_strFindFirst) \
  F(u_strchr) \
  F(u_strchr32) \
  F(u_strrstr) \
  S(u_strFindLast) \
  F(u_strrchr) \
  F(u_strrchr32) \
  F(u_strpbrk) \
  F(u_strcspn) \
  F(u_strspn) \
  F(u_strtok_r) \
  F(u_strcmp) \
  F(u_strcmpCodePointOrder) \
  S(u_strCompare) \
  F(u_strCompareIter) \
  S(u_strCaseCompare) \
  F(u_strncmp) \
  F(u_strncmpCodePointOrder) \
  F(u_strcasecmp) \
  S(u_strncasecmp) \
  S(u_memcasecmp) \
  F(u_strcpy) \
  F(u_strncpy) \
  F(u_uastrcpy) \
  F(u_uastrncpy) \
  F(u_austrcpy) \
  F(u_austrncpy) \
  F(u_memcpy) \
  F(u_memmove) \
  F(u_memset) \
  F(u_memcmp) \
  F(u_memcmpCodePointOrder) \
  F(u_memchr) \
  F(u_memchr32) \
  F(u_memrchr) \
  F(u_memrchr32) \
  F(u_unescape) \
  S(u_unescapeAt) \
  S(u_strToTitle) \
  S(u_strFoldCase) \
  S(u_strToWCS) \
  S(u_strFromWCS) \
  S(u_strToUTF8) \
  S(u_strFromUTF8) \
  S(u_strToUTF8WithSub) \
  S(u_strFromUTF8WithSub) \
  S(u_strFromUTF8Lenient) \
  S(u_strToUTF32) \
  S(u_strFromUTF32) \
  S(u_strToUTF32WithSub) \
  S(u_strFromUTF32WithSub) \
  S(u_strToJavaModifiedUTF8) \
  S(u_strFromJavaModifiedUTF8WithSub) \
\
  F(u_hasBinaryProperty) \
  F(u_isULowercase) \
  F(u_isUUppercase) \
  F(u_getIntPropertyValue) \
  F(u_getIntPropertyMinValue) \
  F(u_getIntPropertyMaxValue) \
  F(u_charDirection) \
  F(u_isMirrored) \
  F(u_charMirror) \
  F(u_getBidiPairedBracket) \
  F(u_charType) \
  F(u_enumCharTypes) \
  F(u_getCombiningClass) \
  F(u_islower) \
  F(u_isupper) \
  F(u_istitle) \
  F(u_isdigit) \
  F(u_isxdigit) \
  F(u_isalpha) \
  F(u_isUAlphabetic) \
  F(u_isalnum) \
  F(u_isdefined) \
  F(u_isbase) \
  F(u_iscntrl) \
  F(u_isISOControl) \
  F(u_isspace) \
  F(u_isJavaSpaceChar) \
  F(u_isWhitespace) \
  F(u_isblank) \
  F(u_isUWhiteSpace) \
  F(u_isprint) \
  F(u_isgraph) \
  F(u_ispunct) \
  F(u_isIDStart) \
  F(u_isIDPart) \
  F(u_isIDIgnorable) \
  F(u_isJavaIDStart) \
  F(u_isJavaIDPart) \
  F(u_charDigitValue) \
  F(u_getNumericValue) \
  F(u_digit) \
  F(u_forDigit) \
  F(u_foldCase) \
  F(u_getUnicodeVersion) \
  F(u_charAge) \
  F(uscript_getScript) \
  F(uscript_hasScript) \
  S(uscript_getScriptExtensions) \
  S(uscript_getShortName) \
  F(ublock_getCode) \
  F(u_charName) \
  F(u_getPropertyName) \
  F(u_getPropertyEnum) \
  F(u_getPropertyValueName) \
  F(u_getPropertyValueEnum) \
  F(u_tolower) \
  F(u_toupper) \
  F(u_totitle) \
  F(u_charFromName) \
  S(u_enumCharNames) \
\
  F(ucnv_compareNames) \
  F(ucnv_open) \
  F(ucnv_openU) \
  F(ucnv_openCCSID) \
  F(ucnv_openPackage) \
  S(ucnv_safeClone) \
  F(ucnv_close) \
  S(ucnv_getSubstChars) \
  S(ucnv_setSubstChars) \
  S(ucnv_setSubstString) \
  S(ucnv_getInvalidChars) \
  S(ucnv_getInvalidUChars) \
  F(ucnv_reset) \
  F(ucnv_resetToUnicode) \
  F(ucnv_resetFromUnicode) \
  F(ucnv_getMaxCharSize) \
  F(ucnv_getMinCharSize) \
  S(ucnv_getDisplayName) \
  F(ucnv_getName) \
  F(ucnv_getCCSID) \
  F(ucnv_getPlatform) \
  F(ucnv_getType) \
  F(ucnv_getStarters) \
  S(ucnv_getUnicodeSet) \
  F(ucnv_getToUCallBack) \
  F(ucnv_getFromUCallBack) \
  S(ucnv_setToUCallBack) \
  S(ucnv_setFromUCallBack) \
  S(ucnv_fromUnicode) \
  S(ucnv_toUnicode) \
  S(ucnv_fromUChars) \
  S(ucnv_toUChars) \
  S(ucnv_getNextUChar) \
  S(ucnv_convertEx) \
  S(ucnv_convert) \
  S(ucnv_toAlgorithmic) \
  S(ucnv_fromAlgorithmic) \
  F(ucnv_flushCache) \
  F(ucnv_countAvailable) \
  F(ucnv_getAvailableName) \
  F(ucnv_openAllNames) \
  F(ucnv_countAliases) \
  F(ucnv_getAlias) \
  F(ucnv_getAliases) \
  F(ucnv_openStandardNames) \
  F(ucnv_countStandards) \
  F(ucnv_getStandard) \
  F(ucnv_getStandardName) \
  F(ucnv_getCanonicalName) \
  F(ucnv_getDefaultName) \
  F(ucnv_setDefaultName) \
  F(ucnv_fixFileSeparator) \
  F(ucnv_isAmbiguous) \
  F(ucnv_setFallback) \
  F(ucnv_usesFallback) \
  S(ucnv_detectUnicodeSignature) \
  F(ucnv_fromUCountPending) \
  F(ucnv_toUCountPending) \
  F(ucnv_isFixedWidth) \
\
  S(ucnv_cbFromUWriteBytes) \
  F(ucnv_cbFromUWriteSub) \
  S(ucnv_cbFromUWriteUChars) \
  S(ucnv_cbToUWriteUChars) \
  F(ucnv_cbToUWriteSub) \
\
  F(uset_openEmpty) \
  F(uset_open) \
  F(uset_openPattern) \
  S(uset_openPatternOptions) \
  F(uset_close) \
  F(uset_clone) \
  F(uset_isFrozen) \
  F(uset_freeze) \
  F(uset_cloneAsThawed) \
  F(uset_set) \
  S(uset_applyPattern) \
  S(uset_applyIntPropertyValue) \
  S(uset_applyPropertyAlias) \
  F(uset_resemblesPattern) \
  S(uset_toPattern) \
  F(uset_add) \
  F(uset_addAll) \
  F(uset_addRange) \
  F(uset_addString) \
  F(uset_addAllCodePoints) \
  F(uset_remove) \
  F(uset_removeRange) \
  F(uset_removeString) \
  F(uset_removeAll) \
  F(uset_retain) \
  F(uset_retainAll) \
  F(uset_compact) \
  F(uset_complement) \
  F(uset_complementAll) \
  F(uset_clear) \
  F(uset_closeOver) \
  F(uset_removeAllStrings) \
  F(uset_isEmpty) \
  F(uset_contains) \
  F(uset_containsRange) \
  F(uset_containsString) \
  F(uset_indexOf) \
  F(uset_charAt) \
  F(uset_size) \
  F(uset_getItemCount) \
  S(uset_getItem) \
  F(uset_containsAll) \
  F(uset_containsAllCodePoints) \
  F(uset_containsNone) \
  F(uset_containsSome) \
  S(uset_span) \
  S(uset_spanBack) \
  S(uset_spanUTF8) \
  S(uset_spanBackUTF8) \
  F(uset_equals) \
  S(uset_serialize) \
  F(uset_getSerializedSet) \
  F(uset_setSerializedToOne) \
  F(uset_serializedContains) \
  F(uset_getSerializedRangeCount) \
  S(uset_getSerializedRange) \
\
  F(uidna_openUTS46) \
  F(uidna_close) \
  S(uidna_labelToASCII) \
  S(uidna_labelToUnicode) \
  S(uidna_nameToASCII) \
  S(uidna_nameToUnicode) \
  S(uidna_labelToASCII_UTF8) \
  S(uidna_labelToUnicodeUTF8) \
  S(uidna_nameToASCII_UTF8) \
  S(uidna_nameToUnicodeUTF8) \
\
  S(utrie2_openFromSerialized) \
  S(utrie2_openDummy) \
  F(utrie2_get32) \
  S(utrie2_enum) \
  F(utrie2_open) \
  F(utrie2_clone) \
  F(utrie2_cloneAsThawed) \
  F(utrie2_close) \
  S(utrie2_set32) \
  S(utrie2_setRange32) \
  F(utrie2_freeze) \
  F(utrie2_isFrozen) \
  S(utrie2_serialize) \
  F(utrie2_getVersion) \
  S(utrie2_swap) \
  S(utrie2_swapAnyVersion) \
  F(utrie2_fromUTrie) \
  F(utrie2_get32FromLeadSurrogateCodeUnit) \
  S(utrie2_enumForLeadSurrogate) \
  S(utrie2_set32ForLeadSurrogateCodeUnit) \
  S(utrie2_internalU8NextIndex) \
  S(utrie2_internalU8PrevIndex) \
\
  F(uloc_getDefault) \
  F(uloc_setDefault) \
  S(uloc_getLanguage) \
  S(uloc_getScript) \
  S(uloc_getCountry) \
  S(uloc_getVariant) \
  S(uloc_getName) \
  S(uloc_canonicalize) \
  F(uloc_getISO3Language) \
  F(uloc_getISO3Country) \
  F(uloc_getLCID) \
  S(uloc_getDisplayLanguage) \
  S(uloc_getDisplayScript) \
  S(uloc_getDisplayCountry) \
  S(uloc_getDisplayVariant) \
  S(uloc_getDisplayKeyword) \
  S(uloc_getDisplayKeywordValue) \
  S(uloc_getDisplayName) \
  F(uloc_getAvailable) \
  F(uloc_countAvailable) \
  F(uloc_getISOLanguages) \
  F(uloc_getISOCountries) \
  S(uloc_getParent) \
  S(uloc_getBaseName) \
  F(uloc_openKeywords) \
  S(uloc_getKeywordValue) \
  S(uloc_setKeywordValue) \
  F(uloc_isRightToLeft) \
  F(uloc_getCharacterOrientation) \
  F(uloc_getLineOrientation) \
  S(uloc_acceptLanguageFromHTTP) \
  S(uloc_acceptLanguage) \
  S(uloc_getLocaleForLCID) \
  S(uloc_addLikelySubtags) \
  S(uloc_minimizeSubtags) \
  S(uloc_forLanguageTag) \
  S(uloc_toLanguageTag) \
\
  S(ubrk_open) \
  S(ubrk_openRules) \
  S(ubrk_safeClone) \
  F(ubrk_close) \
  S(ubrk_setText) \
  F(ubrk_setUText) \
  F(ubrk_current) \
  F(ubrk_next) \
  F(ubrk_previous) \
  F(ubrk_first) \
  F(ubrk_last) \
  F(ubrk_preceding) \
  F(ubrk_following) \
  F(ubrk_getAvailable) \
  F(ubrk_countAvailable) \
  F(ubrk_isBoundary) \
  F(ubrk_getRuleStatus) \
  S(ubrk_getRuleStatusVec) \
  F(ubrk_getLocaleByType) \
  F(ubrk_refreshUText) \
\
  S(utext_openUChars) \
\
  S(UCNV_FROM_U_CALLBACK_STOP) \
  S(UCNV_TO_U_CALLBACK_STOP) \
  S(UCNV_FROM_U_CALLBACK_SKIP) \
  S(UCNV_FROM_U_CALLBACK_SUBSTITUTE) \
  S(UCNV_FROM_U_CALLBACK_ESCAPE) \
  S(UCNV_TO_U_CALLBACK_SKIP) \
  S(UCNV_TO_U_CALLBACK_SUBSTITUTE) \
  S(UCNV_TO_U_CALLBACK_ESCAPE) \


