
#define SSL_LIST(F, S) \
  S(SSL_version) \
  S(SSL_shutdown) \
  S(SSL_new) \
  S(SSL_free) \
  S(SSL_read) \
  S(SSL_write) \
  S(SSL_do_handshake) \
  S(SSL_get_session) \
  S(SSL_get_error) \
  S(SSL_get_current_cipher) \
  S(SSL_get_cipher_by_value) \
  S(SSL_get_extms_support) \
  S(SSL_get0_alpn_selected) \
  S(SSL_get0_certificate_types) \
  S(SSL_get0_ocsp_response) \
  S(SSL_get0_signed_cert_timestamp_list) \
  S(SSL_get_ex_data_X509_STORE_CTX_idx) \
  S(SSL_get_ex_data) \
  S(SSL_get_ex_new_index) \
  S(SSL_get_server_key_exchange_hash) \
  S(SSL_get_peer_cert_chain) \
  S(SSL_get_client_CA_list) \
  S(SSL_get_secure_renegotiation_support) \
  S(SSL_certs_clear) \
  S(SSL_export_keying_material) \
  S(SSL_enable_ocsp_stapling) \
  S(SSL_enable_signed_cert_timestamps) \
  S(SSL_enable_tls_channel_id) \
  S(SSL_set_options) \
  S(SSL_set_alpn_protos) \
  S(SSL_set_cipher_list) \
  S(SSL_set_max_version) \
  S(SSL_set_min_version) \
  S(SSL_set_bio) \
  S(SSL_set_session) \
  S(SSL_set_tlsext_host_name) \
  S(SSL_set_connect_state) \
  S(SSL_set_renegotiate_mode) \
  S(SSL_set_private_key_digest_prefs) \
  S(SSL_set_private_key_method) \
  S(SSL_set1_chain) \
  S(SSL_set1_tls_channel_id) \
  S(SSL_set_ex_data) \
  S(SSL_set_mode) \
  S(SSL_clear_mode) \
  S(SSL_clear_options) \
  S(SSL_use_certificate) \
  S(SSL_CIPHER_get_name) \
  S(SSL_CIPHER_get_id) \
  S(SSL_CIPHER_get_bits) \
  S(SSL_CTX_new) \
  S(SSL_CTX_free) \
  S(SSL_CIPHER_is_DHE) \
  S(SSL_CTX_set_cert_cb) \
  S(SSL_CTX_set_cert_verify_callback) \
  S(SSL_CTX_set_verify) \
  S(SSL_CTX_set_quiet_shutdown) \
  S(SSL_CTX_set_next_proto_select_cb) \
  S(SSL_CTX_set_session_cache_mode) \
  S(SSL_CTX_sess_set_new_cb) \
  S(SSL_CTX_add_client_custom_ext) \
  S(SSL_SESSION_free) \
  S(SSL_SESSION_up_ref) \
  S(SSL_SESSION_get_key_exchange_info) \
  S(SSL_session_reused) \
  S(SSLv23_client_method) \
  

